name = "my-web-app"
compatibility_date = "2026-06-07"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://enroll-api-1onw.onrender.com/v1"